name: social_services
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.8
  carousel_slider: ^4.2.1
  provider: ^6.0.5
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.1
  flutter_rating_bar: ^4.0.1
  google_sign_in: ^6.1.6
  firebase_auth: ^4.15.0
  sign_in_with_apple: ^6.0.0
  firebase_core: ^2.31.1
  another_flushbar: ^1.12.30
  cloud_firestore: ^4.13.3
  image_picker: ^1.0.4
  firebase_storage: ^11.5.5
  cached_network_image: ^3.3.1
  awesome_snackbar_content: ^0.1.3
  moyasar: ^2.0.2
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^17.0.0
  overlay_support: ^2.1.0
  permission_handler: ^11.3.0
  circular_countdown_timer: ^0.2.3
  shimmer: ^3.0.0
  intl_phone_field: ^3.2.0
  country_code_picker: ^3.0.0
  quiver: ^3.2.1
  velocity_x: ^4.1.2
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.1
  hive_flutter: ^1.1.0
  dropdown_button2: ^2.3.9
  audioplayers: ^6.0.0
  audio_session: ^0.1.19
  just_audio: ^0.9.38
  build_runner: ^2.4.10
  hive_generator: ^2.0.1
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Black.ttf
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-ExtraLight.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Thin.ttf  

  